import { register, login, googleLogin, logout, auth, onAuthStateChanged, resendVerification } from './auth.js';

const style=document.createElement('style');
style.textContent=`.sh-auth-backdrop{position:fixed;inset:0;background:#0009;z-index:100;display:none;align-items:center;justify-content:center;padding:20px}.sh-auth-backdrop.open{display:flex}.sh-auth-card{width:min(430px,100%);background:#fffdfa;border:1px solid #ddd6ca;padding:34px;position:relative;box-shadow:0 25px 80px #0004}.sh-auth-card h2{font:600 34px/1.1 Georgia,serif;margin:0 0 8px;color:#171613}.sh-auth-card p{font:12px/1.6 Arial,sans-serif;color:#706b63}.sh-auth-close{position:absolute;right:18px;top:14px;font-size:28px;border:0;background:none;cursor:pointer}.sh-auth-card label{display:block;font:600 10px Arial,sans-serif;letter-spacing:.08em;text-transform:uppercase;margin:15px 0;color:#555}.sh-auth-card input{display:block;width:100%;margin-top:7px;padding:13px;border:1px solid #ddd6ca;background:#fff;border-radius:0;outline:none;font-size:14px}.sh-auth-card input:focus{border-color:#171613}.sh-auth-submit,.sh-google{width:100%;height:46px;margin-top:16px;border:1px solid #171613;cursor:pointer;font-weight:700;font-size:11px;letter-spacing:.08em;text-transform:uppercase}.sh-auth-submit{background:#171613;color:#fff}.sh-google{background:#fff;color:#171613}.sh-auth-switch,.sh-resend{display:block;margin:18px auto 0;border:0;background:none;text-decoration:underline;cursor:pointer;font-size:11px}.sh-auth-msg{text-align:center;min-height:18px;color:#8b6a37!important}.sh-hidden{display:none!important}`;
document.head.appendChild(style);

const backdrop=document.createElement('div');backdrop.className='sh-auth-backdrop';backdrop.innerHTML=`<div class="sh-auth-card" role="dialog" aria-modal="true"><button class="sh-auth-close" aria-label="Close">×</button><div class="sh-auth-body"><p style="letter-spacing:.18em;color:#8b6a37;font-weight:700">SONALI'S HANDCRAFTS</p><h2 id="shAuthTitle">Welcome back</h2><p id="shAuthSubtitle">Sign in to your account.</p><form id="shAuthForm"><div id="shNameWrap" class="sh-hidden"><label>Name<input id="shName" autocomplete="name"></label></div><label>Email<input id="shEmail" type="email" autocomplete="email" required></label><label>Password<input id="shPassword" type="password" minlength="6" autocomplete="current-password" required></label><button class="sh-auth-submit" type="submit" id="shSubmit">Sign in</button></form><button class="sh-google" id="shGoogle">Continue with Google</button><button class="sh-auth-switch" id="shSwitch">Create an account</button><button class="sh-resend sh-hidden" id="shResend">Resend verification email</button><p class="sh-auth-msg" id="shMsg"></p></div></div>`;document.body.appendChild(backdrop);
const $=id=>document.getElementById(id);let signup=false;
function open(){backdrop.classList.add('open');$('shEmail').focus()}function close(){backdrop.classList.remove('open')}
function setMode(){signup=!signup;$('shAuthTitle').textContent=signup?'Create your account':'Welcome back';$('shAuthSubtitle').textContent=signup?'Join Sonali\'s Handcrafts.':'Sign in to your account.';$('shNameWrap').classList.toggle('sh-hidden',!signup);$('shSubmit').textContent=signup?'Create account':'Sign in';$('shSwitch').textContent=signup?'Already have an account? Sign in':'Create an account';$('shMsg').textContent='';$('shResend').classList.add('sh-hidden')}
$('loginButton')?.addEventListener('click',open);$('.sh-auth-close')?.addEventListener('click',close);backdrop.addEventListener('click',e=>{if(e.target===backdrop)close()});$('shSwitch').addEventListener('click',setMode);
$('shAuthForm').addEventListener('submit',async e=>{e.preventDefault();$('shMsg').textContent='Please wait…';try{const email=$('shEmail').value.trim(),password=$('shPassword').value;const user=signup?await register(email,password,$('shName').value.trim()):await login(email,password);if(signup&&!user.emailVerified){$('shMsg').textContent='Account created. Check your email to verify your address.';$('shResend').classList.remove('sh-hidden')}else{$('shMsg').textContent=`Welcome${user.displayName?', '+user.displayName:''}!`;setTimeout(close,700)}}catch(err){console.error(err);$('shMsg').textContent=err.code?.includes('auth/')?err.message.replace('Firebase: ','').replace(/ \(auth\/.*\)\.?/,''): 'Something went wrong. Please try again.'}});
$('shGoogle').addEventListener('click',async()=>{try{const user=await googleLogin();$('shMsg').textContent=`Welcome${user.displayName?', '+user.displayName:''}!`;setTimeout(close,700)}catch(err){$('shMsg').textContent='Google sign-in was cancelled or failed.'}});
$('shResend').addEventListener('click',async()=>{try{await resendVerification();$('shMsg').textContent='Verification email sent again.'}catch(_){$('shMsg').textContent='Could not resend the email.'}});
onAuthStateChanged(auth,user=>{const btn=$('loginButton');if(!btn)return;if(user){btn.textContent='Account';btn.title=user.email||'Account'}else{btn.textContent='♙';btn.title='Login'}});