const authStyle=document.createElement('style');authStyle.textContent=`.auth-overlay{position:fixed;inset:0;z-index:100;background:rgba(0,0,0,.65);display:none;align-items:center;justify-content:center;padding:20px}.auth-overlay.open{display:flex}.auth-modal{width:min(430px,100%);background:#fffdfa;border:1px solid #ddd6ca;padding:34px;position:relative;box-shadow:0 25px 80px rgba(0,0,0,.3)}.auth-close{position:absolute;right:15px;top:10px;font-size:28px}.auth-logo{display:block;width:150px;height:58px;object-fit:contain;margin:0 auto 12px}.auth-modal h2{font:600 32px/1.1 Georgia,serif;text-align:center;margin:8px 0}.auth-modal>p,.auth-message{text-align:center;color:#706b63;font-size:12px}.auth-modal form{margin-top:22px}.auth-modal label{display:block;font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;margin:13px 0}.auth-modal input{display:block;width:100%;padding:13px;border:1px solid #ddd6ca;margin-top:7px;outline:none;background:#fff;font-size:14px}.auth-submit{width:100%;margin-top:8px}.google-btn{width:100%;height:46px;margin-top:12px;border:1px solid #ddd6ca;background:#fff;font-size:11px;font-weight:700}.auth-switch{text-align:center;margin-top:18px!important}.auth-switch button{font-weight:700;text-decoration:underline}.auth-message{min-height:18px;color:#8b6a37!important}@media(max-width:600px){.auth-modal{padding:28px 20px}.auth-logo{width:130px}.auth-modal h2{font-size:28px}}`;document.head.appendChild(authStyle);
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAnalytics } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-analytics.js";
import { getFirestore, collection, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, GoogleAuthProvider, signInWithPopup, sendEmailVerification, updateProfile, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
const firebaseConfig={apiKey:"AIzaSyBeCA_wut1H1_RyOKLfcLXSj-GCb8GOxkY",authDomain:"sonalis-handcrafts.firebaseapp.com",projectId:"sonalis-handcrafts",storageBucket:"sonalis-handcrafts.firebasestorage.app",messagingSenderId:"275433297737",appId:"1:275433297737:web:be6eee5d452c77245dec98",measurementId:"G-4FE43YQE09"};
const firebaseApp=initializeApp(firebaseConfig);const db=getFirestore(firebaseApp);const auth=getAuth(firebaseApp);try{getAnalytics(firebaseApp)}catch(_){}
const products=[{id:1,name:'Terracotta Vase',desc:'Hand-shaped ceramic décor',price:699,class:'p1'},{id:2,name:'Woven Wall Basket',desc:'Natural fiber wall art',price:849,class:'p2'},{id:3,name:'Clay Tea Set',desc:'A warm, rustic everyday set',price:1199,class:'p3'},{id:4,name:'Artisan Candle',desc:'Hand-poured soy wax',price:499,class:'p4'}];let cart=[];
const productsEl=document.getElementById('products'),countEl=document.getElementById('cartCount'),itemsEl=document.getElementById('cartItems'),totalEl=document.getElementById('cartTotal'),panel=document.getElementById('cartPanel'),overlay=document.getElementById('overlay'),nav=document.getElementById('nav'),menuToggle=document.getElementById('menuToggle');
function money(n){return `₹${n.toLocaleString('en-IN')}`}function renderProducts(){productsEl.innerHTML=products.map(p=>`<article class="product"><div class="product-image ${p.class}" aria-hidden="true"></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span><button class="add" onclick="addToCart(${p.id})">Add to cart</button></div></div></article>`).join('')}function addToCart(id){const p=products.find(x=>x.id===id),existing=cart.find(x=>x.id===id);existing?existing.qty++:cart.push({...p,qty:1});renderCart();openCart()}function removeFromCart(id){cart=cart.filter(x=>x.id!==id);renderCart()}function renderCart(){countEl.textContent=cart.reduce((s,x)=>s+x.qty,0);if(!cart.length){itemsEl.innerHTML='<div class="empty">Your cart is ready for something handmade.</div>';totalEl.textContent=money(0);return}itemsEl.innerHTML=cart.map(x=>`<div class="cart-item"><div><strong>${x.name}</strong><small>${x.qty} × ${money(x.price)}</small></div><button onclick="removeFromCart(${x.id})">Remove</button></div>`).join('');totalEl.textContent=money(cart.reduce((s,x)=>s+x.price*x.qty,0))}function openCart(){panel.classList.add('open');overlay.classList.add('open')}function closeCart(){panel.classList.remove('open');overlay.classList.remove('open')}function closeMenu(){nav.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}
document.getElementById('cartButton').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;overlay.onclick=closeCart;menuToggle.onclick=()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open))};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.getElementById('checkout').onclick=async()=>{if(!cart.length){alert('Your cart is empty.');return}try{await addDoc(collection(db,'orders'),{items:cart.map(({id,name,price,qty})=>({id,name,price,qty})),total:cart.reduce((s,x)=>s+x.price*x.qty,0),status:'pending',createdAt:serverTimestamp()});alert('Order saved successfully. Payment integration can be added next.');cart=[];renderCart();closeCart()}catch(error){console.error(error);alert('Please check your Firestore configuration.')}};
document.getElementById('newsletterForm').addEventListener('submit',async e=>{e.preventDefault();const email=e.target.querySelector('input').value.trim(),message=document.getElementById('formMessage');try{await addDoc(collection(db,'newsletterSubscribers'),{email,createdAt:serverTimestamp()});message.textContent='Thanks! You’re on the list.';e.target.reset()}catch(error){console.error(error);message.textContent='Please check your Firestore configuration.'}});
const authOverlay=document.getElementById('authOverlay'),accountButton=document.getElementById('accountButton'),authClose=document.getElementById('authClose'),authForm=document.getElementById('authForm'),authSwitch=document.getElementById('authSwitch'),authName=document.getElementById('authName'),authEmail=document.getElementById('authEmail'),authPassword=document.getElementById('authPassword'),authSubmit=document.getElementById('authSubmit'),authTitle=document.getElementById('authTitle'),authSubtitle=document.getElementById('authSubtitle'),authMessage=document.getElementById('authMessage'),googleLogin=document.getElementById('googleLogin');let signupMode=false;
function openAuth(){authOverlay.classList.add('open');authOverlay.setAttribute('aria-hidden','false');setTimeout(()=>authEmail.focus(),50)}function closeAuth(){authOverlay.classList.remove('open');authOverlay.setAttribute('aria-hidden','true')}function setAuthMode(){signupMode=!signupMode;authTitle.textContent=signupMode?'Create your account':'Welcome back';authSubtitle.textContent=signupMode?"Join Sonali's Handcrafts.":"Sign in to your Sonali's Handcrafts account.";authName.hidden=!signupMode;authName.required=signupMode;authSubmit.innerHTML=signupMode?'Create account <span>→</span>':'Sign in <span>→</span>';authSwitch.innerHTML=signupMode?'Already have an account? <button type="button">Sign in</button>':'New here? <button type="button">Create an account</button>';authMessage.textContent=''}
accountButton.addEventListener('click',openAuth);authClose.addEventListener('click',closeAuth);authOverlay.addEventListener('click',e=>{if(e.target===authOverlay)closeAuth()});authSwitch.addEventListener('click',setAuthMode);
authForm.addEventListener('submit',async e=>{e.preventDefault();authMessage.textContent='Please wait…';try{let user;if(signupMode){const r=await createUserWithEmailAndPassword(auth,authEmail.value.trim(),authPassword.value);user=r.user;await updateProfile(user,{displayName:authName.value.trim()});await addDoc(collection(db,'users'),{uid:user.uid,name:authName.value.trim(),email:user.email,createdAt:serverTimestamp()});await sendEmailVerification(user);authMessage.textContent='Account created! Check your email to verify your address.'}else{const r=await signInWithEmailAndPassword(auth,authEmail.value.trim(),authPassword.value);user=r.user;authMessage.textContent=`Welcome${user.displayName?', '+user.displayName:''}!`;setTimeout(closeAuth,700)}}catch(err){console.error(err);authMessage.textContent=err.message.replace(/^Firebase:\s*/,'').replace(/\s*\(auth\/[^)]*\)\.?$/,'')}});
googleLogin.addEventListener('click',async()=>{try{const r=await signInWithPopup(auth,new GoogleAuthProvider());authMessage.textContent=`Welcome${r.user.displayName?', '+r.user.displayName:''}!`;setTimeout(closeAuth,700)}catch(err){authMessage.textContent='Google sign-in was cancelled or failed.'}});
onAuthStateChanged(auth,user=>{accountButton.setAttribute('aria-label',user?`Account: ${user.email}`:'Login');accountButton.title=user?user.email:'Login'});
window.addToCart=addToCart;window.removeFromCart=removeFromCart;window.sonaliFirebase={app:firebaseApp,db,auth};renderProducts();renderCart();
import './mobile-fix.js';