import { supabase } from './supabase.js';

const SITE_URL='https://sonalishandcrafts.vercel.app';
const authStyle=document.createElement('style');authStyle.textContent=`.auth-overlay{position:fixed;inset:0;z-index:100;background:rgba(0,0,0,.65);display:none;align-items:center;justify-content:center;padding:20px}.auth-overlay.open{display:flex}.auth-modal{width:min(430px,100%);background:#fffdfa;border:1px solid #ddd6ca;padding:34px;position:relative;box-shadow:0 25px 80px rgba(0,0,0,.3)}.auth-close{position:absolute;right:15px;top:10px;font-size:28px}.auth-logo{display:block;width:150px;height:58px;object-fit:contain;margin:0 auto 12px}.auth-modal h2{font:600 32px/1.1 Georgia,serif;text-align:center;margin:8px 0}.auth-modal>p,.auth-message{text-align:center;color:#706b63;font-size:12px}.auth-modal form{margin-top:22px}.auth-modal label{display:block;font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;margin:13px 0}.auth-modal input{display:block;width:100%;padding:13px;border:1px solid #ddd6ca;margin-top:7px;outline:none;background:#fff;font-size:14px}.auth-submit{width:100%;margin-top:8px}.google-btn{width:100%;height:46px;margin-top:12px;border:1px solid #ddd6ca;background:#fff;font-size:11px;font-weight:700}.auth-switch{text-align:center;margin-top:18px!important}.auth-switch button{font-weight:700;text-decoration:underline}.auth-message{min-height:18px;color:#8b6a37!important}@media(max-width:600px){.auth-modal{padding:28px 20px}.auth-logo{width:130px}.auth-modal h2{font-size:28px}}`;document.head.appendChild(authStyle);

const products=[{id:1,name:'Terracotta Vase',desc:'Hand-shaped ceramic décor',price:699,class:'p1'},{id:2,name:'Woven Wall Basket',desc:'Natural fiber wall art',price:849,class:'p2'},{id:3,name:'Clay Tea Set',desc:'A warm, rustic everyday set',price:1199,class:'p3'},{id:4,name:'Artisan Candle',desc:'Hand-poured soy wax',price:499,class:'p4'}];
let cart=JSON.parse(localStorage.getItem('sonaliCart')||'[]');
const productsEl=document.getElementById('products'),countEl=document.getElementById('cartCount'),itemsEl=document.getElementById('cartItems'),totalEl=document.getElementById('cartTotal'),panel=document.getElementById('cartPanel'),overlay=document.getElementById('overlay'),nav=document.getElementById('nav'),menuToggle=document.getElementById('menuToggle');
function money(n){return `₹${n.toLocaleString('en-IN')}`}function renderProducts(){productsEl.innerHTML=products.map(p=>`<article class="product"><div class="product-image ${p.class}" aria-hidden="true"></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span><button class="add" onclick="addToCart(${p.id})">Add to cart</button></div></div></article>`).join('')}function saveCart(){localStorage.setItem('sonaliCart',JSON.stringify(cart))}function addToCart(id){const p=products.find(x=>x.id===id),existing=cart.find(x=>x.id===id);existing?existing.qty++:cart.push({...p,qty:1});saveCart();renderCart();openCart()}function removeFromCart(id){cart=cart.filter(x=>x.id!==id);saveCart();renderCart()}function renderCart(){countEl.textContent=cart.reduce((s,x)=>s+x.qty,0);if(!cart.length){itemsEl.innerHTML='<div class="empty">Your cart is ready for something handmade.</div>';totalEl.textContent=money(0);return}itemsEl.innerHTML=cart.map(x=>`<div class="cart-item"><div><strong>${x.name}</strong><small>${x.qty} × ${money(x.price)}</small></div><button onclick="removeFromCart(${x.id})">Remove</button></div>`).join('');totalEl.textContent=money(cart.reduce((s,x)=>s+x.price*x.qty,0))}function openCart(){panel.classList.add('open');overlay.classList.add('open')}function closeCart(){panel.classList.remove('open');overlay.classList.remove('open')}function closeMenu(){nav.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}
document.getElementById('cartButton').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;overlay.onclick=closeCart;menuToggle.onclick=()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open))};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.getElementById('checkout').onclick=()=>{if(!cart.length){alert('Your cart is empty.');return}alert('Checkout is ready for the next payment integration.');};
document.getElementById('newsletterForm').addEventListener('submit',e=>{e.preventDefault();const email=e.target.querySelector('input').value.trim(),message=document.getElementById('formMessage');localStorage.setItem('newsletterEmail',email);message.textContent='Thanks! You’re on the list.';e.target.reset()});

const authOverlay=document.getElementById('authOverlay'),accountButton=document.getElementById('accountButton'),authClose=document.getElementById('authClose'),authForm=document.getElementById('authForm'),authSwitch=document.getElementById('authSwitch'),authName=document.getElementById('authName'),authEmail=document.getElementById('authEmail'),authPassword=document.getElementById('authPassword'),authSubmit=document.getElementById('authSubmit'),authTitle=document.getElementById('authTitle'),authSubtitle=document.getElementById('authSubtitle'),authMessage=document.getElementById('authMessage'),googleLogin=document.getElementById('googleLogin');
let signupMode=false;
function openAuth(){authOverlay.classList.add('open');authOverlay.setAttribute('aria-hidden','false');setTimeout(()=>authEmail.focus(),50)}function closeAuth(){authOverlay.classList.remove('open');authOverlay.setAttribute('aria-hidden','true')}function setAuthMode(){signupMode=!signupMode;authTitle.textContent=signupMode?'Create your account':'Welcome back';authSubtitle.textContent=signupMode?"Join Sonali's Handcrafts.":"Sign in to your Sonali's Handcrafts account.";authName.hidden=!signupMode;authName.required=signupMode;authSubmit.innerHTML=signupMode?'Create account <span>→</span>':'Sign in <span>→</span>';authSwitch.innerHTML=signupMode?'Already have an account? <button type="button">Sign in</button>':'New here? <button type="button">Create an account</button>';authMessage.textContent=''}
function friendlyError(error){const m=(error?.message||'Something went wrong.').replace(/^AuthApiError:\s*/,'');if(m.toLowerCase().includes('invalid login credentials'))return 'Incorrect email or password.';if(m.toLowerCase().includes('email not confirmed'))return 'Please verify your email before signing in.';if(m.toLowerCase().includes('user already registered'))return 'An account with this email already exists. Try signing in.';return m}
accountButton.addEventListener('click',openAuth);authClose.addEventListener('click',closeAuth);authOverlay.addEventListener('click',e=>{if(e.target===authOverlay)closeAuth()});authSwitch.addEventListener('click',setAuthMode);
authForm.addEventListener('submit',async e=>{e.preventDefault();authMessage.textContent='Please wait…';authSubmit.disabled=true;try{if(signupMode){const {data,error}=await supabase.auth.signUp({email:authEmail.value.trim(),password:authPassword.value,options:{data:{name:authName.value.trim(),full_name:authName.value.trim()},emailRedirectTo:SITE_URL}});if(error)throw error;authMessage.textContent=data.session?'Account created successfully!':'Account created. Check your email to verify your address.'}else{const {data,error}=await supabase.auth.signInWithPassword({email:authEmail.value.trim(),password:authPassword.value});if(error)throw error;authMessage.textContent=`Welcome${data.user?.user_metadata?.name?', '+data.user.user_metadata.name:''}!`;setTimeout(closeAuth,700)}}catch(err){console.error(err);authMessage.textContent=friendlyError(err)}finally{authSubmit.disabled=false}});
googleLogin.addEventListener('click',async()=>{authMessage.textContent='Google login is currently unavailable. Please use email and password.'});
supabase.auth.onAuthStateChange((event,session)=>{const user=session?.user;accountButton.setAttribute('aria-label',user?`Account: ${user.email}`:'Login');accountButton.title=user?user.email:'Login';if(event==='SIGNED_IN'&&!signupMode){authMessage.textContent=`Welcome${user?.user_metadata?.name?', '+user.user_metadata.name:''}!`}});
window.addToCart=addToCart;window.removeFromCart=removeFromCart;window.sonaliSupabase=supabase;renderProducts();renderCart();
